# Netlify configuration for UvLizer landing page

[build]
  publish = "./"
  command = "npm run build"

# Shopify proxy redirect for cart API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/shopify-proxy/:splat"
  status = 200
  force = true

# Shopify credentials should remain secure on the server
[[redirects]]
  from = "/.env"
  to = "/404.html"
  status = 404
  force = true

# Elevar proxy for analytics
[[redirects]]
  from = "/elevar/*"
  to = "https://hits.getelevar.com/:splat"
  status = 200
  force = true

# Handle SPA routing for single page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#static"
  command = "npm run dev"
  port = 3000
  publish = "./"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  # Set environment variables for build
#  SHOPIFY_STORE_DOMAIN = "fsnmhb-6m.myshopify.com"
  # Storefront API token is set in Netlify UI as a secret

# Map edge functions to paths
[[edge_functions]]
  path = "/api/create-user-id"
  function = "create-user-id" 